// <auto-generated />
using BratnavaFC.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BratnavaFC.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320130000_AddPolls")]
    partial class AddPolls
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
