// <auto-generated />
using BratnavaFC.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BratnavaFC.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506120000_AddRankIcons")]
    partial class AddRankIcons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Full snapshot is maintained in AppDbContextModelSnapshot.cs
        }
    }
}
