// <auto-generated />
using System;
using BratnavaFC.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BratnavaFC.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217220314_UseMatchPlayersToScoreGoals")]
    partial class UseMatchPlayersToScoreGoals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BratnavaFC.Domain.Entities.GoalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssistMatchPlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MatchPlayerEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MatchPlayerEntityId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScorerMatchPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TimeSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssistMatchPlayerId");

                    b.HasIndex("GroupId");

                    b.HasIndex("MatchPlayerEntityId");

                    b.HasIndex("MatchPlayerEntityId1");

                    b.HasIndex("ScorerMatchPlayerId");

                    b.HasIndex("MatchId", "AssistMatchPlayerId");

                    b.HasIndex("MatchId", "ScorerMatchPlayerId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.GroupAdminEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupAdmins");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.GroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ScheduleMatchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.GroupSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefaultDayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("DefaultKickoffTime")
                        .HasColumnType("interval");

                    b.Property<string>("DefaultPlaceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("GroupSettings");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.MatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<Guid?>("TeamAColorId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TeamAGoals")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeamBColorId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TeamBGoals")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeamAColorId");

                    b.HasIndex("TeamBColorId");

                    b.HasIndex("GroupId", "PlayedAt");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.MatchPlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("InviteResponse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool?>("IsMvp")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<short>("Team")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VotedForId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique();

                    b.HasIndex("MatchId", "PlayerId", "GroupId")
                        .IsUnique();

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.PlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("InactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsGoalkeeper")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SkillPoints")
                        .HasColumnType("numeric");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.TeamColorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("HexValue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "Name");

                    b.ToTable("TeamColors");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("InactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.VoteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VotedForId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VotedForId");

                    b.HasIndex("VoterId");

                    b.HasIndex("MatchId", "VoterId")
                        .IsUnique();

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.GoalEntity", b =>
                {
                    b.HasOne("BratnavaFC.Domain.Entities.MatchPlayerEntity", "AssistMatchPlayer")
                        .WithMany()
                        .HasForeignKey("AssistMatchPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BratnavaFC.Domain.Entities.GroupEntity", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BratnavaFC.Domain.Entities.MatchEntity", "Match")
                        .WithMany("Goals")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BratnavaFC.Domain.Entities.MatchPlayerEntity", null)
                        .WithMany("GoalsScored")
                        .HasForeignKey("MatchPlayerEntityId");

                    b.HasOne("BratnavaFC.Domain.Entities.MatchPlayerEntity", null)
                        .WithMany("GoalsAssisted")
                        .HasForeignKey("MatchPlayerEntityId1");

                    b.HasOne("BratnavaFC.Domain.Entities.MatchPlayerEntity", "ScorerMatchPlayer")
                        .WithMany()
                        .HasForeignKey("ScorerMatchPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssistMatchPlayer");

                    b.Navigation("Group");

                    b.Navigation("Match");

                    b.Navigation("ScorerMatchPlayer");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.GroupAdminEntity", b =>
                {
                    b.HasOne("BratnavaFC.Domain.Entities.GroupEntity", "Group")
                        .WithMany("Admins")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BratnavaFC.Domain.Entities.UserEntity", "User")
                        .WithMany("Admins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.GroupSettingsEntity", b =>
                {
                    b.HasOne("BratnavaFC.Domain.Entities.GroupEntity", null)
                        .WithOne()
                        .HasForeignKey("BratnavaFC.Domain.Entities.GroupSettingsEntity", "GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.MatchEntity", b =>
                {
                    b.HasOne("BratnavaFC.Domain.Entities.GroupEntity", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BratnavaFC.Domain.Entities.TeamColorEntity", "TeamAColor")
                        .WithMany()
                        .HasForeignKey("TeamAColorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BratnavaFC.Domain.Entities.TeamColorEntity", "TeamBColor")
                        .WithMany()
                        .HasForeignKey("TeamBColorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("TeamAColor");

                    b.Navigation("TeamBColor");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.MatchPlayerEntity", b =>
                {
                    b.HasOne("BratnavaFC.Domain.Entities.GroupEntity", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BratnavaFC.Domain.Entities.MatchEntity", "Match")
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BratnavaFC.Domain.Entities.PlayerEntity", "Player")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.PlayerEntity", b =>
                {
                    b.HasOne("BratnavaFC.Domain.Entities.GroupEntity", "Group")
                        .WithMany("Players")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BratnavaFC.Domain.Entities.UserEntity", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("BratnavaFC.Domain.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.TeamColorEntity", b =>
                {
                    b.HasOne("BratnavaFC.Domain.Entities.GroupEntity", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.VoteEntity", b =>
                {
                    b.HasOne("BratnavaFC.Domain.Entities.MatchEntity", "Match")
                        .WithMany("Votes")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BratnavaFC.Domain.Entities.MatchPlayerEntity", "VotedFor")
                        .WithMany("ReceivedVotes")
                        .HasForeignKey("VotedForId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BratnavaFC.Domain.Entities.MatchPlayerEntity", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("VotedFor");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.GroupEntity", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.MatchEntity", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Players");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.MatchPlayerEntity", b =>
                {
                    b.Navigation("GoalsAssisted");

                    b.Navigation("GoalsScored");

                    b.Navigation("ReceivedVotes");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.PlayerEntity", b =>
                {
                    b.Navigation("MatchPlayers");
                });

            modelBuilder.Entity("BratnavaFC.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
