name: Fly Deploy

on:
  push:
    branches:
      - main   # Se quiser deploy só na main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet restore BratnavaFC.sln

      - run: dotnet test BratnavaFC.sln --no-build

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY }}
